name: Deploy Nuxt site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # IMPORTANTE: Ruta exacta a la carpeta donde está tu package.json
        working-directory: portfolio/app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        # Al estar en working-directory, esto buscará el package.json correcto
        run: npm install

      - name: Static HTML export with Nuxt
        run: npm run generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Ruta desde la raíz del repositorio hasta la carpeta de salida de Nuxt 3
          path: portfolio/app/.output/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
